name: PlayerInfos
version: '${project.version}'
main: ch.ksrminecraft.playerinfos.PlayerInfos
api-version: '1.20'
commands:
  playerinfo:
    description: Gibt eine Statistik des Spierls aus
    aliases: [pi]
